- README.md
- docs/index.md
- matfree/backend/control_flow.py
- matfree/montecarlo.py
using `map` instead of `scan` has the same low-memory implications, benchmarks are indistinguishable, and `map` is  far easier to maintain.
Resolves #100
> Replace mean_loop with mean_map and expose target_fun

- matfree/decomp.py
- tests/test_decomp/test_gkl_full_reortho.py
> Catch wrong depth in a ValueError for GKL

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- matfree/backend/typing.py
- pyproject.toml
Now running with python 3.9+ instead of 3.8+ because this is what JAX requires.
> Update required python versions and update pre-commit hook

- README.md
The previous links were outdated.
And since this was not the first time this happened, the "Tutorial" section in the readme has been rephrased now.
> Update links in documentation

- matfree/backend/np.py
- matfree/decomp.py
- matfree/slq.py
- tests/test_decomp/test_bidiagonal_full_reortho.py
- tests/test_decomp/test_svd.py
- tests/test_decomp/test_tridiagonal_full_reortho.py
This is an assumption in the algorithm.
This PR introduces a new flag for the two Lanczos-algorithms (validate_unit_2_norm=True/False), which check the norm of the input and mark it as unusable if the norm is not 1. The default is False, which is backward-compatible.
> Implement validation of a unit two norm in Lanczos-style decompositions

- matfree/slq.py
- tests/test_slq/test_logdet_product.py
- tests/test_slq/test_logdet_spd.py
For any vector $v$, evaluating $v^\top f(A) v$ with SLQ using max-order Lanczos should be exact. 
Before this PR, this is only true for Rademacher-distributed input vectors (and in expectation, for normally-distributed input vectors).
After this PR, it is true for arbitrary input vectors.
> Make SLQ integrands behave correctly for arbitrary input vectors

- matfree/lanczos.py
- tests/test_lanczos/test_alg_bidiagonal_full_reortho.py
- tests/test_lanczos/test_alg_tridiagonal_full_reortho.py
As the title states.
This PR breaks backwards compatibility (but the next release is already breaking, so we might as well make the remaining breaking changes now).
Why?
Because both decompose_fori_loop, as well as the Lanczos-decomposition algorithms, have always been closely tied together (one did not work without the other). Now, this is more clear because only one of them is public.
As a side result, matrix-decomposition algorithms now implement parametrised matrix-vector products, and the matrix-decomposition algorithms share an output type with Hutchinson-, Lanczos-, and Chebyshev-style methods.
> Merge decomposition-algorithms with decompose_fori_loop

- matfree/lanczos.py
- tests/test_lanczos/test_integrand_logdet_product.py
- tests/test_lanczos/test_integrand_logdet_spd.py
- tests/test_lanczos/test_integrand_schatten_norm.py
- tutorials/1_log_determinants.py
- tutorials/2_pytree_logdeterminants.py
Rename stochastic Lanczos quadrature functions:
* `integrand*_spd` -> `integrand_spd*` 
* `integrand*_product` -> `integrand_product*` 
Now, related functions are grouped together in the documentation.
> Rename lanczos.integrand_* functions

- matfree/backend/testing.py
- matfree/pinv.py
- tests/test_pinv/test_pseudo_inverse_correct.py
I have never used it, I suspect no one else has ever used it, and it clutters the namespace.
It will be removed in v0.0.17 or v0.1.0, whichever happens first.
If someone needs it, please create an issue.
> Deprecate matfree.pinv

- matfree/funm.py
- matfree/funm_trace.py
- matfree/hutchinson.py
- matfree/lanczos.py
- tests/test_funm/test_funm_chebyshev.py
- tests/test_funm/test_funm_lanczos_spd.py
- tests/test_funm_trace/test_integrand_logdet_product.py
- tests/test_funm_trace/test_integrand_logdet_spd.py
- tests/test_funm_trace/test_integrand_schatten_norm.py
- tutorials/1_log_determinants.py
- tutorials/2_pytree_logdeterminants.py
This PR moves all f(A)v and trace(f(A)) code to separate modules.
This deletes matfree.polynomial and clears much of matfree.lanczos.
The motivation is that we want to have functions that yield similar results in the same module (instead of functions that use similar algorithms behind the scenes). We also want to trim down the Lanczos module a bit, because more code is coming  there :eyes:
> Create dedicated `funm` and `funm_trace` modules for functions of matrices

- matfree/funm.py
- matfree/funm_trace.py
- matfree/hutchinson.py
- matfree/lanczos.py
- tests/test_funm/test_funm_lanczos_sym.py
- tests/test_funm_trace/test_integrand_logdet_sym.py
- tutorials/1_log_determinants.py
- tutorials/2_pytree_logdeterminants.py
Many Lanczos-tridiagonalisation functions came with the `spd` suffix, but those functions only require symmetric matrices, not symmetric positive definite matrices.
> Rename misnamed functions

- matfree/backend/config.py
- matfree/backend/func.py
- matfree/backend/np.py
- matfree/decomp.py
- matfree/funm.py
- matfree/stochtrace_funm.py
- matfree/test_util.py
- tests/test_decomp/test_hessenberg_adjoint.py
- tests/test_decomp/test_tridiag_sym.py
- tests/test_decomp/test_tridiag_sym_adjoint.py
This PR implements gradients of the Lanczos and Arnoldi iterations according to the paper [under this link](https://arxiv.org/abs/2405.17277).
The essence of this change is that we can now take efficient reverse-mode derivatives ("gradients") through Lanczos and Arnoldi, which is useful for all sorts of machine-learning models.
As a side result, this PR fixes #181.
> Implement differentiable Lanczos and Arnoldi iterations

- matfree/decomp.py
- matfree/eig.py
- matfree/funm.py
- tests/test_decomp/test_bidiag.py
* Hide all bidiag()-internal functions in the bidiag() namespace
* Make bidiag() normalise the initial vector internally (instead of verifying that it has been normalised). This changes the output signature of bidiag!
> Improve the consistency of bidiag() and tridiag_sym()

- Makefile
- README.md
- matfree/decomp.py
- matfree/eig.py
- matfree/funm.py
- matfree/stochtrace.py
- scripts/tutorials_to_py_light.py
- tests/test_decomp/test_bidiag.py
- tests/test_decomp/test_hessenberg.py
- tests/test_decomp/test_hessenberg_adjoint.py
- tests/test_decomp/test_tridiag_sym.py
- tests/test_decomp/test_tridiag_sym_adjoint.py
- tests/test_funm/test_funm_lanczos_sym.py
- tests/test_funm/test_integrand_funm_logdet_product.py
- tests/test_funm/test_integrand_funm_logdet_sym.py
- tests/test_funm/test_integrand_funm_schatten_norm.py
- tests/test_stochtrace/test_diagonal.py
- tests/test_stochtrace/test_frobeniusnorm_squared.py
- tests/test_stochtrace/test_trace.py
- tests/test_stochtrace/test_trace_and_diagonal.py
- tests/test_stochtrace/test_wrap_moments.py
- tutorials/1_log_determinants.py
- tutorials/2_pytree_logdeterminants.py
- tutorials/3_uncertainty_quantification.py
- tutorials/4_control_variates.py
- tutorials/5_vector_calculus.py
- tutorials/6_low_memory_trace_estimation.py
**Many of Matfree's functions manipulate matrix-vector products before calling other Matfree-functions, which leads to unnecessary code duplication in Matfree's current state.** For example, `funm.integrand_funm_*` flattens matrix-vector product code before calling decompositions from decomp.py. Since `matvec`-style arguments are currently part of the algorithm-constructors instead of the `estimate`-style functions that these constructors return, it is difficult to patch together methods. As a symptom, every matrix decomposition has a twin in `funm.integrand_funm_*`, even though the overall code for these integrands does not change much.
**This PR solves this issue by making `matvec` an argument to `estimate`, not an argument to `construct_algorithm`.**
The changes affect most of Matfree …
> Move matvec to estimation instead of algorithm-construction to avoid future code duplication

- matfree/decomp.py
- matfree/eig.py
- matfree/funm.py
- tests/test_decomp/test_bidiag.py
- tests/test_decomp/test_tridiag_sym.py
- tests/test_decomp/test_tridiag_sym_adjoint.py
- tests/test_funm/test_funm_lanczos_sym.py
Most applications of tridiagonalisation and bidiatonalisation require materialising the tri/bidiagonal matrices and doing linear algebra with those dense matrices.
Currently, all applications of bi/tridiagonalisation (including funm, eig, and tests) have a function like "todense_tri/bidiagonal", and there is not a single use of the coefficients without materialising the matrices in the entire library.
**This PR introduces an option for materialising those matrices as part of the decompositions.**
This `materialize` flag is set to `True` by default, but can be set to `False` to recover the previous implementation.
Functions of matrices require that `materialize` is set to True.
As a result, future version of Matfree can write integrand_funm agnostic of the decomposition, which will …
> Add a 'materialize' option to tridiag() and bidiag() to simplify downstream applications

- matfree/decomp.py
- matfree/eig.py
- matfree/funm.py
- tests/test_decomp/test_bidiag.py
- tests/test_eig/test_svd_partial.py
- tests/test_funm/test_integrand_funm_product_logdet.py
- tests/test_funm/test_integrand_funm_product_schatten_norm.py
- tutorials/1_log_determinants.py
Why? To allow a user to choose between different kinds of (e.g.) reorthogonalisation.
Thus, this PR resolves #196.
As a side-result, bidiag() does not need information about the matrix shape anymore and reads it off the inputs at execution time instead.
> Make integrand_funm_product_* expect algorithms as inputs (not algorithm parameters)

- .github/release.yml
Via [this tutorial](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes).
> Configure automatically generated release notes to organize how PRs are displayed

- .pre-commit-config.yaml
- matfree/decomp.py
- matfree/eig.py
- matfree/funm.py
- tests/test_decomp/test_bidiag.py
- tests/test_eig/test_svd_partial.py
- tests/test_funm/test_integrand_funm_product_logdet.py
- tests/test_funm/test_integrand_funm_product_schatten_norm.py
- tutorials/1_log_determinants.py
Resolves #228.
**This change breaks the current API** because all bidiagonalisation-based algorithms no longer require vector-matrix products to be passed to the decomposition. This includes:
- `decomp.bidiag`
- `eig.svd_partial`
- `funm.integrand_funm_product`
Instead of requiring the vector-Jacobian product, all functions now use `jax.vjp` to turn a matrix-vector product into a vector-matrix product. We don't use `jax.linear_transpose` because the forward pass is required for bidiagonalisation anyway, so we can do evaluation+transposition in a single call to `vjp` instead of a call to, each, forward pass and transposition.
The next version number will reflect the backwards-incompatible change.
> Automatically implement vector matrix products with `jax.vjp`

- matfree/backend/testing.py
- matfree/decomp.py
- matfree/eig.py
- matfree/funm.py
- tests/test_decomp/test_bidiag.py
- tests/test_decomp/test_consistency.py
- tests/test_decomp/test_hessenberg.py
- tests/test_decomp/test_hessenberg_adjoint.py
- tests/test_decomp/test_tridiag_sym.py
- tests/test_decomp/test_tridiag_sym_adjoint.py
- tests/test_eig/test_svd_partial.py
- tests/test_funm/test_funm_chebyshev.py
- tests/test_funm/test_integrand_funm_product_logdet.py
- tests/test_funm/test_integrand_funm_product_schatten_norm.py
- tests/test_funm/test_integrand_funm_sym_logdet.py
- tutorials/1_log_determinants.py
- tutorials/2_pytree_logdeterminants.py
- tutorials/7_matrix_functions.py
Resolves #222.
- Now, this parameter is called 'num_matvecs' everywhere. The main reason for choosing 'num_matvecs' over 'krylov_rank' and so on is that it is easier to understand for everyone unfamiliar with the inner workings of Krylov subspaces. 
It is also less ambiguous because the rank of the Krylov space is typically `num_matvecs + 1` instead of `num_matvecs`, but this is a convention that matfree takes (for code simplicity). Here, too, does the parameter name `num_matvecs` improve clarity.
- All decompositions (bidiag, tridiag_sym, hessenberg) now interpret "num_matvecs" identically which means they yield the same shapes of outputs depending on the values of `num_matvecs`. Previously, that was not the case because bidiagonalisation interpreted the 'order' parameter differently to …
> Rename all `krylov_depth`-like parameters to `num_matvecs` and ensure consistency between decomps

- matfree/backend/linalg.py
- matfree/eig.py
- tests/test_eig/test_eig_partial.py
- tests/test_eig/test_eigh_partial.py
- tests/test_eig/test_svd_partial.py
This PR changes the output signatures of the functions in eig.py.
For a rank-k eigendecomposition (respectively singular value decomposition), the eigenvalue array has shape (k,).
For an n-dimensional matrix, the previous eigenvector-shape was (n,k); now, it is (k,n).
Why?
- It improves the clarity of the output containing a "stack of eigenvectors", ie the i-th element is the i-th eigenvector
- It more easily generalises to pytree-valued states (see #226, which is where this change came up)
- It simplifies vmapping over the solution of the partial eigenvalue decompositions (eg for custom gradients).
Notably, this deviates from the output shapes of the decompositions in numpy.linalg. But the above reasons are sufficiently strong to ignore this inconsistency.
This change breaks the existing …
> Change the ordering of eigen-/singular-vectors in `eig.py` 

- matfree/backend/np.py
- matfree/backend/tree.py
- matfree/eig.py
- tests/test_eig/test_svd_partial.py
Resolves #226. Uses the implementation suggested in the thread (essentially, liberal application of jax.eval_shape and jax.flatten_util.ravel_pytree). 
This change is backwards compatible (since all the breaking changes have been released under v0.2.0 already).
> Make the partial SVD compatible with Pytrees

- .github/workflows/ci.yaml
- .github/workflows/doc-publish.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
- README.md
- matfree/backend/np.py
- matfree/decomp.py
- matfree/test_util.py
- pyproject.toml
- scripts/readme_to_dev_docs.py
- scripts/tutorials_to_py_light.py
- tests/test_decomp/test_hessenberg_adjoint.py
- tests/test_funm/test_integrand_funm_product_logdet.py
- tests/test_funm/test_integrand_funm_product_schatten_norm.py
I don't understand why some tests suddenly fail (maybe the PRNG semantics have changed slightly?). 
A slight weakening of the test criteria makes them pass. I assume everything's fine, because the src hasn't been touched.
> Bump Python and pre-commit hook versions

- .pre-commit-config.yaml
- matfree/lstsq.py
Decompositions like `hessenberg()` have a `custom_vjp` argument, but `lsmr()` had a `use_custom_vjp` argument. This PR changes this to ensure consistency between functions.
> Rename 'use_custom_vjp' to 'custom_vjp' to ensure consistency with the rest of the code

- matfree/decomp.py
- tests/test_decomp/test_hessenberg_adjoint.py
Currently, the code doesn't work in this case anyway so it's better to have an informed error than an unexpected crash.
> Raise a ValueError in the Hessenberg-adjoints if num_matvecs=0 to catch an existing error

- matfree/backend/testing.py
- matfree/lstsq.py
- tests/test_lstsq.py
This is a breaking change, because `damp` and `x0` are now arguments to the lsmr function. Previously, `damp` was passed to the constructor and `x0` wasn't passed at all. Everything else is the same so I expected that almost every user will not notice any difference.
> Allow initial guesses to be passed to LSMR
